[![min0's GitHub stats](https://github-readme-stats.vercel.app/api?username=JSK0406&show_icons=true&theme=darka&count_private=true)](https://github.com/anuraghazra/github-readme-stats)
[![Solved.ac Profile](http://mazassumnida.wtf/api/v2/generate_badge?boj=mingyi2006)](https://solved.ac/mingyi2006/)


<!--
**JSK0406/JSK0406** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.


Here are some ideas to get you started:



- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
